### ISSUE TITLE
Cuckoo Service - Error running service: 'task_id'

### ISSUE THREAD

**Issue by landw1re** [crits/crits_services#117]
I've got the Cuckoo Service all configured and the communication between CRITs and Cuckoo seems fine but when I kickoff of the service on a binary I receive the following error in the log

**Error running service: 'task_id'**

I have the **Existing task ID** field set to **0** as indicated by the instructions (i.e. "***Use '0' to run a new analysis***")

Has anyone else experienced this issue? Any thoughts on resolution?

**Comment by christauff** [comment]
Just revert the **/cuckoo/utils/api.py** to a earlier version. The current version is returning **task_ids** not **task_id**.

We just fixed this issue earlier this week.
