### ISSUE TITLE
Error when using PassiveTotal Service

### ISSUE THREAD

**Issue by johncwrobel** [crits/crits_services#126]
I set up the PassiveTotal Service add-on to my CRITs install and configured it with my API key from PassiveTotal. To test it, I went into PassiveTotal and found an IP address, which I then added to CRITs, and then tried to use the PassiveTotal Service to analyze it. This resulted in the following error: 
![passivetotal_service_error](https://cloud.githubusercontent.com/assets/3334741/8208629/a05f53e4-14d6-11e5-8a7b-65eea03d514e.PNG)

I tried looking around for anyone else encountering this error but didn't find anything. Any suggestions on how to fix this error?

Thanks,

**Comment by gtback** [comment]
You should be able to work around it by adding a trailing slash to the `pt_query_url` in your configuration. 

I think the actual error is coming from [these lines](https://github.com/crits/crits_services/blob/aa239a658cf28006b600eb5308ac566329a3aede/passivetotal_service/__init__.py#L142-L144), and shouldn't be too difficult to fix.

**Comment by johncwrobel** [comment]
That fixed it. Funny that I had to add in a slash so that it could be removed later. Thanks for the help!

**Comment by wxsBSD** [comment]
Sorry, copy/paste mistake on my part. Fixed now.

**Comment by gtback** [comment]
Thanks, @wxsBSD . I figured it would be that easy but you know the code better than I do :wink:
