### ISSUE TITLE
whois bug?

### ISSUE THREAD

**Issue by villain** [crits/crits_services#130]
not sure if anyone else is experiencing this; i have the whois service setup to work with pyDat. however for domains which have never been updated after being impoted (eg: have only been imported once), i receive an error:

INFO 2015-07-20 16:41:05,065 crits.services.handlers Running whois on 558fc2a3f7a84d34861dbf58, execute=process
DEBUG 2015-07-20 16:41:05,066 crits.services.handlers Adding task 03939bb5-906b-4015-8f6a-7ff5788457a3 {Service: whois, Id: 558fc2a3f7a84d34861dbf58}
ERROR 2015-07-20 16:41:05,315 crits.services.core Error running service whois
Traceback (most recent call last):
  File "/data/crits/crits/services/core.py", line 438, in execute
    self.run(self.current_task.obj, config)
  File "/data/crits_services/whois_service/__init__.py", line 210, in run
    self.do_pydat_query(obj, config)
  File "/data/crits_services/whois_service/__init__.py", line 155, in do_pydat_query
    versions.append(data['Version'])
KeyError: 'Version'
DEBUG 2015-07-20 16:41:06,552 crits.services.core Finished analysis 03939bb5-906b-4015-8f6a-7ff5788457a3

could probably be fixed by setting a base version, to catch instances when the Version key doesnt exist

**Comment by villain** [comment]
ah, looks like there might also be a dataVersion key, perhaps in earlier versions of the whoisxmlapi dataset?

"dataVersion": 1

**Comment by villain** [comment]
i have it working with the below:

        for data in results['data']:
            if 'dataVersion' in data:
                versions.append(data['dataVersion'])
                versions_check = data['dataVersion']
                self._info('Version found: %s' % data['dataVersion'])
            else:
                versions.append(data['Version'])
                versions_check = data['Version']
                self._info('Version found: %s' % data['Version'])

        versions.sort()
        latest = versions[-1]

        for data in results['data']:
            # Only grab the most recent version.
            if versions_check != latest:
                continue

**Comment by lqaz** [comment]
@mgoffin This issue should be closed, a fix has been merged.

**Comment by mgoffin** [comment]
Thanks!
