### ISSUE TITLE
cuckoo service not running on triage

### ISSUE THREAD

**Issue by markedoe** [crits/crits_services#137]
Hi,

the cuckoo service is not running on triage although others are running well.

Thanks.

**Comment by mgoffin** [comment]
https://github.com/crits/crits/issues/545

**Comment by wxsBSD** [comment]
I'm going to close this one and suggest the discussion happen in #545 as @mgoffin is suggesting. The two are certainly identical issues.

**Comment by markedoe** [comment]
thanks didn't see the other issue.
