### ISSUE TITLE
[Email] Investigate phishtank integration

### ISSUE THREAD

**Issue by mgoffin** [crits/crits_services#14]
It seems this site is becoming popular with verifying phishing attempts. I can't speak to the quality of the data, etc. but might be worth looking into.

**Comment by evoxco** [comment]
Hi mgoffin
We have a threat feed aggregation service which includes Phishing data feeds as well such as Phishtank. Feel free to try the crits service from https://github.com/EvoxComputing/c1fapp_service.git
Thx
