### ISSUE TITLE
ThreatRecon integration

### ISSUE THREAD

**Issue by elhoim** [crits/crits_services#145]
A good service to lookup IPs & DNS.

https://threatrecon.co/
API details: https://threatrecon.co/api

**Comment by webstergd** [comment]
Hey David,

CRITs does have a service for Threat Recon. Does this not fit your needs?
If not, what would you need the service to do in addition?

https://github.com/crits/crits_services/tree/master/threatrecon_service

**Comment by elhoim** [comment]
Sorry for missing it, just checked my browser when i searched i had a typo: treatrecon instead of threatrecon.

**Comment by webstergd** [comment]
Treat recon is so much better then threat recon. :-)
 And thanks for submitting a request!
