### ISSUE TITLE
Unable to upload IP addresses via STIX

### ISSUE THREAD

**Issue by natarajah** [crits/crits_services#149]
Unable to upload IP addresses via STIX - type object 'IPTypes' has no attribute 'IPv4_ADDRESS'

I am using a STIX 1.1.1 document found here https://raw.github.com/STIXProject/schemas/version_1.1.1/samples/STIX_IP_Watchlist.xml

When attempting to import the document, I get the following errors:

Nothing Imported
Failed
Address 	ID: example:Object-1980ce43-8e03-490b-863a-ea404d12242e

type object 'IPTypes' has no attribute 'IPv4_ADDRESS'

Currently running crits 4-master, and the following dependencies for taxii_service:

M2Crypto
- libtaxii-1.1.102 and its dependencies
- cybox==2.1.0.11
- stix==1.1.1.5

**Comment by mgoffin** [comment]
I think that should fix your issue. Can you pull master for crits_services and give it a go? Github closed the issue on me because I referenced the issue in the commit. If it doesn't work I'll reopen :)

**Comment by natarajah** [comment]
Works now!  Thanks!!
