### ISSUE TITLE
Pdf2txt KeyError: '_id'

### ISSUE THREAD

**Issue by myntric** [crits/crits_services#178]
When attempting to run pdf2txt on a PDF sample within CRITs, the service does not provide any results.  The configuration is valid and all dependencies do exist:

Configuration
pdf2txt_path : /usr/bin/pdftotext
antiword_path : /usr/bin/antiword
Results
This service produced no results.

The debug logs reads as follows:

INFO 2015-11-18 10:28:56,745 crits.services.handlers Running pdf2txt on 564c8c0b41e71c2c10d7775e, execute=process
DEBUG 2015-11-18 10:28:56,747 crits.services.handlers Adding task 95b1ed4e-c6b9-4fb3-9544-772f7050582c {Service: pdf2txt, Id: 564c8c0b41e71c2c10d7775e}
ERROR 2015-11-18 10:28:57,275 crits.services.core Error running service pdf2txt
Traceback (most recent call last):
  File "/data/crits/crits/services/core.py", line 438, in execute
    self.run(self.current_task.obj, config)
  File "/data/crits_services/pdf2txt_service/__init__.py", line 157, in run
    raw_obj = class_from_id("RawData", res["_id"])
KeyError: '_id'
DEBUG 2015-11-18 10:28:57,333 crits.services.core Finished analysis 95b1ed4e-c6b9-4fb3-9544-772f7050582c

I am able to run /usr/bin/pdftotext manually against the same PDF file and export it to a text file successfully.

**Comment by frbapolkosnik** [comment]
Which version of CRITs are you running?

**Comment by myntric** [comment]
4-master.  Just cloned and re-installed a week ago.

**Comment by frbapolkosnik** [comment]
I'm going to replace pdf2txt_service with textract_service (if you want to play with that you can find it here https://github.com/frbapolkosnik/crits_services/tree/master/textract_service)
