### ISSUE TITLE
Metacap Viewer error while trying to view pcap file

### ISSUE THREAD

**Issue by affvei** [crits/crits_services#184]
ERROR!
Must be AJAX.

I'd already installed everything

**Comment by frbapolkosnik** [comment]
Do you have anything in the webserver or CRITs logs?

Perhaps you could go through the crits-user mailing list before dumping unconfirmed bugs here. Just saying...

**Comment by frbapolkosnik** [comment]
After looking at views.py, it looks like there are only 3 cases where you can get this message. Perhaps try enabling debug (webserver restart is required) and try to get some more details.
