### ISSUE TITLE
Yara service not allowing configuring

### ISSUE THREAD

**Issue by cjdupreez** [crits/crits_services#186]
For some reason, in the web interface, I'm unable to save my configuration options for the Yara service. This is the only service that has issues saving. I specify my signature directory and my signature files separated on a new line for each rule, but when clicking 'submit', the button just stays pressed for a little bit then releases without saving my changes. Have a look:

![image](https://cloud.githubusercontent.com/assets/5132774/12094900/5cb8a234-b2d9-11e5-93e5-035217e95371.png)

Any thoughts?

**Comment by frbapolkosnik** [comment]
Make sure the you have the dependencies installed for yara, take a look at DEPENDENCIES file in yara_services folder. You might want to grab the latest Yara version and installing it manually. Take a look there: http://yara.readthedocs.org/en/latest/gettingstarted.html

Please check that the folder has the same ownership/permissions as the parent folder.

Start small with a single signature file.

Do you see anything in crits.log?

**Comment by cjdupreez** [comment]
I installed the latest version of Yara and specified a single yara rule to import and it still hangs. Nothing in the crits.log file looked related. Permissions and ownership on the yara rules are the same as the Apache service running CRITs. One thing I did notice was even after updating Yara, the CRITs service page for configuring yara still reports it's running version 2.0.1 like it did in the screenshot I shared. That may have something to do with it...

**Comment by frbapolkosnik** [comment]
Hmm, for one, you seem to be using a git checkout that's not up-to-date (the latest version of crits yara_service is 2.0.2). Second, you might need to try to see if you have the old yara libraries/binaries on the box, and try to remove them.

**Comment by cjdupreez** [comment]
Updated CRITs and CRITs services with git pulls, re-ran the bootstrap for CRITs services and the yara config web page now shows 2.0.2 but still having the same issue. Also verified that no other versions of yara are installed on my system. CRITs log still shows nothing of use. Any other possible suggestions?

Thanks,
-Cornel.

**Comment by pinowudi** [comment]
Are you using the distributed CRITS 3 or the current 4_stable?

**Comment by cjdupreez** [comment]
Current stable version 4.

**Comment by frbapolkosnik** [comment]
Try running yara from command line first, then run python interactive she'll,  and type in: "import yara", and see if that gives you any errors

**Comment by cjdupreez** [comment]
Works from the command line and works fine in the python interpreter.

**Comment by frbapolkosnik** [comment]
It looks like the error might have something to do with the "Signature directory", since it's highlighted, perhaps a leading or trailing space?

**Comment by cjdupreez** [comment]
Wow. Missing a trailing slash. That fixed it, thanks!

**Comment by cjdupreez** [comment]
Just realized, in addition to me forgetting the trailing slash, another reason the configuration fails to save is because it looks like some yara rules are failing a check. I'm not sure what check that is, but I'm trying to import the yara rules I cloned from here https://github.com/Yara-Rules/rules.git. It imports the first 3 just fine, but when I try to import Anthem_DeepPanda.yar it fails. It fails with numerous others as well. Can anyone else verify?

**Comment by apolkosnik** [comment]
Whoever submitted rovnix_downloader_sinkhole_check.yar to Yara-Rules had M$ word quotation marks in there, once they accept my fix, it should work just fine.

To generate a list that you can copy and paste, you can run:
cd Yara-Rules/rules ; find . | grep -E '.yar?$' >/tmp/yara-rules.txt

That way you can get a descriptive error on what failed. 

If you try to roll everything into a single entry in Signature Files listview by using the "include" statements, it's not that easy to debug, as it will perceive all the included rules as a single file you might run into scope conflicts.

**Comment by apolkosnik** [comment]
Anthem_DeepPanda.yar imports "pe", and it doesn't seem to use it. But if you have older Yara/libyara versions it might not be there.

Try removing the whole line containing *import "pe"* and if it works, then you probably have some ancient libyara in your path.

**Comment by cjdupreez** [comment]
Removing import "pe" fixed it. Thanks again.
