### ISSUE TITLE
ThreatExchange (nonexisting field (submitter_count))

### ISSUE THREAD

**Issue by thelok** [crits/crits_services#209]
I understand ThreatExchange is still under development, but just want to document this here.

Queried for malware families => variants => dropped by => Import

```
'status_code': 400, 'message': u'(#100) Tried accessing nonexisting field (submitter_count) on node type (MalwareAnalysis)', 'type': u'OAuthException'
```

**Comment by mgoffin** [comment]
Interesting. If you view that specific Malware Analyses via the web I assume the field doesn't exist either?

**Comment by thelok** [comment]
How do you view it via the web?

**Comment by mgoffin** [comment]
https://graph.facebook.com/<id>/?access_token=foo|bar

**Comment by thelok** [comment]
Man, getting the ID was really difficult. But the answer is no it doesn't exist in the web JSON result either.

**Comment by thelok** [comment]
There's a victim count though.

**Comment by mgoffin** [comment]
What if you add "&metadata=1" to the URL. does it show submitter_count as a viable field?

**Comment by thelok** [comment]
A whole bunch of extra fields but no submitter count

**Comment by thelok** [comment]
On a separate note, in the query builder the "Status" field is never used when submitting the form, probably because it has an id="text".

**Comment by thelok** [comment]
And "importing" IP_ADDRESS types don't work because the CRITs vocab doesn't define a IP_ADDRESS type =) Sounds like we'll need a mapping or a new type.

**Comment by mgoffin** [comment]
Won't need a new type. We purposely decided to specify whether something is IPv4 or IPv6. Same goes with exporting. It will require you to pick IP_ADDRESS at this time. But we will need to map on import I guess.

**Comment by mgoffin** [comment]
Added a couple things. Hopefully that maps at least the IP_ADDRESS and IP_SUBNET types to IPV4_ADDRESS and IPV4_SUBNET (we really should check to see if we should use v4 or v6). Also removed SUBMITTER_COUNT from something we query for on import since we don't really use it (still following up with the TX folks as I was unaware it was being removed). Also fixed the Status ID so it's actually "status" now. Let me know if those fixes help anything!

**Comment by mgoffin** [comment]
Ok after discussing with the ThreatExchange folks it seems `submitter_count` was removed from the Graph for all of the ThreatExchange objects. I updated `pytx` to 0.4.1 to support this and also updated the CRITs code again to remove it. You'll need to update to master and to the latest version of `pytx`.

**Comment by thelok** [comment]
That was fast, thanks!
