### ISSUE TITLE
TAXII Service TODO List

### ISSUE THREAD

**Issue by thelok** [crits/crits_services#213]
I'm going to start looking at the TAXII service but I don't know where to start. Can we document some of the major issues or features that are missing for this service so we have a defined list.

For example:

- [ ] Identifying which CRITs vocab types are not supported between CRITs <=> STIX/Cybox
- [ ] Implementing/Fixing STIX Importing via file upload (don't know if this is working or not)
- [ ] TAXII Discovery?

etc.

**Comment by thelok** [comment]
Anyone?

**Comment by mgoffin** [comment]
This is not something on my radar. There are very few, if any, people/organizations I know that actually leverage STIX/TAXII in any meaningful way. This is the reason I moved all of the STIX features over to the service. It wasn't being maintained in core properly and the vast majority of people I came across disliked being forced to use it.

I suspect there might be a handful (at best) of people interested in the TAXII Service, so I wouldn't be deterred if you don't hear anything until those specific people notice and have something to add.

**Comment by frbapolkosnik** [comment]
I'm interested in getting the CRITs <=> STIX/Cybox mapping done, eventually. I think that the second thing you mentioned is part of this anyway, since TAXII is just a pipe to move STIX.

**Comment by brlogan** [comment]
Totally missed this post on Friday.
Improving support for the new CRITs vocabulary is probably the most pressing need. I believe that importing STIX files is currently functional, however it doesn't use the Preview feature. I've done some work toward that, but haven't had a chance to finish it yet.

TAXII Discovery is another feature that should be added.

**Comment by pinowudi** [comment]
DHS just announced Automated Information Service, a TAXII based intelligence service. I expect the need for STIX/TAXII services will grow with more free, potentially high-quality feeds becoming available.

**Comment by thelok** [comment]
I agree with @pinowudi STIX/TAXII might seem dead but there's still a push to use it.

Thanks for the feedback so far, I at least have a starting point now.

**Comment by mgoffin** [comment]
Everywhere I go it's the butt-end of most jokes. But in all seriousness it doesn't solve as many problems as people think. When you have the ability to create "custom objects" which require custom knowledge to parse, it means every feed you ingest is going to require you to look at and parse differently.

Not going to stop anyone from using it, but there's already better solutions out there that people are using heavily with great success.

**Comment by thelok** [comment]
@mgoffin I agree that STIX/TAXII is a big pain and I am still not a fan of it. But what else is there that tries to solve this problem...

> "better solutions out there that people are using heavily with great success."

Care to elaborate on that? =)

**Comment by mgoffin** [comment]
ThreatExchange :) And as you know there's a CRITs service for it already!

**Comment by pinowudi** [comment]
Unfortunately the legal terms for ThreatExchange are still untenable to our legal staff. It’s also a private company and we want the ability to establish our own lanes of dissemination. I like what FB has done, it’s just unusable to our org at present. Any others?

**Comment by MarkDavidson** [comment]
I debated whether or not I should reply, but I felt like it would be OK since I am directly answering a question. @pinowudi, the company I work for has a free product (you can pay for support + enterprise features) that will allow you to set up your own lanes of dissemination called Soltra Edge.

You can download Soltra Edge here: https://forums.soltra.com/index.php?/files/

If you'd like to continue this conversation please contact me off-thread (my Soltra email address is on my GitHub profile).

Thank you.
-Mark

**Comment by frbapolkosnik** [comment]
It seems that all of the types listed at http://stixproject.github.io/data-model/1.2/stixVocabs/IndicatorTypeVocab-1.1/ are not supported in the current version.

**Comment by brlogan** [comment]
The STIX support should be a little better now with the updates in #246.  Still far from perfect, but better.

**Comment by jezkerwin** [comment]
@brlogan Just wanted to thank you for all your hard work on the taxii-service. It's something I've wanted for a while but I'm not a coder so I thankful of what you've done with this service.
Cheers. :-)

**Comment by brlogan** [comment]
@jezkerwin My pleasure! Glad you've found it useful. :)
