### ISSUE TITLE
TAXII service not submitting

### ISSUE THREAD

**Issue by grwerbacher** [crits/crits_services#220]
I'm attempting to setup a taxii connection using the updated taxii service, however when I hit "submit" the feed is not actually saved into the service configurations. Any help?

**Comment by brlogan** [comment]
Strange. Did you figure this out?
When you click the "Submit" button on the feed form, it should immediately save that data to the config unless it encounters an error. For example, if the provided CRITs Source doesn't exist in CRITs, an error should be displayed and the feed form shouldn't be hidden.

When you click "Submit" on the feed form, does it hide the feed form and show the server config form again? Do the server config details get saved, just not the feeds? Any other details you can provide on the behavior?

**Comment by grwerbacher** [comment]
I have not figured this out yet. When I click the submit button, it remains on the feed form and doesn't return to the server config form. I also don't get any errors when clicking submit, it just remains on the form.

**Comment by mgoffin** [comment]
And you've opened up Developer Tools and looked at the request being made and the response you get?

**Comment by grwerbacher** [comment]
![screen shot 2016-06-08 at 2 13 24 pm](https://cloud.githubusercontent.com/assets/13661114/15905861/7780a212-2d84-11e6-9808-1e9dfd2f8abe.png)

I am getting an Internal Server Error when attempting to POST. Above is the info I am using for my feed config.

**Comment by brlogan** [comment]
I'm guessing there is something wrong in the DB with your service configuration.  If you can provide the response body for the POST, or the contents of the taxii_service document in the "services" collection of your DB, then I can probably find the issue.

**Comment by grwerbacher** [comment]
{ "_id" : ObjectId("575acdcc1d41c86ca49864c4"), "schema_version" : 1, "name" : "taxii_service", "config" : { "ns_prefix" : "test", "max_rels" : 200, "namespace" : "http://www.testinstance.com", "create_events" : false, "taxii_servers" : "" }, "compatability_mode" : false, "description" : "Send TAXII messages to a TAXII server.", "status" : "available", "supported_types" : [ ], "version" : "2.1.0", "enabled" : true, "run_on_triage" : true }

**Comment by grwerbacher** [comment]
[TaxiiServiceResponseBody.txt](https://github.com/crits/crits_services/files/309181/TaxiiServiceResponseBody.txt)

Here is the entire response body from the HTTP POST

**Comment by brlogan** [comment]
Very helpful! I found the problem. Sure enough, part of your service configuration is in an unexpected format.  I'll try to figure out how that might have happened and provide a fix.

Did you have an old version of the taxi_service installed previously, or did you just add the current version to your CRITs instance?

**Comment by grwerbacher** [comment]
Thanks for looking into this! I essentially just installed a clean version of CRITs and just used the current version in my CRITs instance. All coming from the master branches.

**Comment by brlogan** [comment]
Okay, I think I have this fixed. Grab the update in #232 and let me know if it works for you.

**Comment by grwerbacher** [comment]
This worked! thank you brlogan, much appreciated

**Comment by brlogan** [comment]
Great! You are welcome, @grwerbacher!
Sounds like this issue can be closed.
