### ISSUE TITLE
TAXII SERVICE - default Confidence and Impact for feeds

### ISSUE THREAD

**Issue by chrisfry** [crits/crits_services#245]
It would be awesome if we could configure/assign default Confidence and Impact when adding a taxii feed. Some feeds I would set to High for both and then implement auto-mitigation with my other crits integration. Currently everything goes in as Unknown/Unknown.

**Comment by brlogan** [comment]
This is something to consider, but we would need to decide what to do when the STIX Indicator actually provides a value for Confidence and Impact.  Should the feed configuration in CRITs override the values in the STIX package, or are they only used when no values are provided in the STIX document?

**Comment by chrisfry** [comment]
I think it should be only if no C/I provided in original STIX (and if you configure it). Otherwise, it should import with the values in the original STIX doc and any adjustments made afterward in CRITs are done through the GUI or some other self-defined mechanism (pymongo scripting etc).

**Comment by chrisfry** [comment]
bump. any more thoughts on this?

**Comment by brlogan** [comment]
I think I'm okay with this and we haven't gotten any objections.
Give me some time and I'll take a closer look.

**Comment by brlogan** [comment]
I think I'm okay with this and we haven't gotten any objections.
Give me some time and I'll take a closer look.

**Comment by brlogan** [comment]
I think I have this working in #256. Please test it out and let me know what you think!
