### ISSUE TITLE
taxii_services: Send to TAXII Server fails with "local variable 'proxy' referenced before assignment"

### ISSUE THREAD

**Issue by packet-rat** [crits/crits_services#249]
Send to TAXII Server fails with "local variable 'proxy' referenced before assignment" In the configuration scenario below (No Proxy, https):

![2016-07-25_19-12-52](https://cloud.githubusercontent.com/assets/3220193/17120713/3fa14bb6-529c-11e6-9a97-32e946e92f27.png)

Example:

![2016-07-25_16-08-57](https://cloud.githubusercontent.com/assets/3220193/17120817/d9e8226c-529c-11e6-9692-01a207ca27e2.png)

![2016-07-25_16-09-15](https://cloud.githubusercontent.com/assets/3220193/17120819/e08c61c8-529c-11e6-9aef-5e8f3af5b19a.png)

![2016-07-25_16-09-30](https://cloud.githubusercontent.com/assets/3220193/17120823/e5ec65a0-529c-11e6-9e21-acf847e89169.png)

Adding a check for HTTP_PROXY before attempting **client.setProxy(proxy)** solved the problem for me.

@ ~ line 1300
### Was
```
# Setup client authentication and proxy communication
        if https:
            client.setUseHttps(True)
        client.setProxy(proxy)
        if akey and lcert and user:
            client.setAuthType(tc.HttpClient.AUTH_CERT_BASIC)
            client.setAuthCredentials({'key_file': akey, 'cert_file': lcert,
                                       'username': user, 'password': pword})
```
### Is
@ ~ line 1300
```
# Setup client authentication and proxy communication
        if https:
            client.setUseHttps(True)
        if settings.HTTP_PROXY:
            client.setProxy(proxy)
        if akey and lcert and user:
            client.setAuthType(tc.HttpClient.AUTH_CERT_BASIC)
            client.setAuthCredentials({'key_file': akey, 'cert_file': lcert,
                                       'username': user, 'password': pword})
```

Didn't know if there was a specific reason to not issue client.setProxy after line ~1258 (similar to the identical code block at line 265):

```

# Get Proxy settings
    if settings.HTTP_PROXY:
        proxy = settings.HTTP_PROXY
        if not proxy.startswith('http://'):
            proxy = 'http://' + proxy
```

```

# Get Proxy settings
    if settings.HTTP_PROXY:
        proxy = settings.HTTP_PROXY
        if not proxy.startswith('http://'):
            proxy = 'http://' + proxy
        client.setProxy(proxy)
```

**Comment by brlogan** [comment]
Oops, good catch, @packet-rat!
This is fixed with PR #250.
