### ISSUE TITLE
Feature Request:  Add UTC Timestamp to STIX Preview File Name

### ISSUE THREAD

**Issue by packet-rat** [crits/crits_services#254]
Feature Request: Replace generic filename of "STIX_preview.xml" for STIX packages created by the taxii_service Preview feature with UTC Timestamp (i.e., "STIX_20160803-191704.xml").

Reason: The taxii_service Preview feature is a very convenient method for creating STIX Packages for development, testing, out-of-band transmission, and import into other tools and frameworks.  Providing a unique, time-stamp based filename enables discrimination, tracking, management of STIX Packages created in this fashion.

```
taxii_service/views.py

-            c_disp = 'attachment; filename="STIX_preview.xml"'
+            utcnow = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
+            c_disp = 'attachment; filename=STIX_' + utcnow + '.xml'
```

**Comment by brlogan** [comment]
I think I have this working in #256. Please test it out and let me know what you think!
