### ISSUE TITLE
pyimpfuzzy install fails

### ISSUE THREAD

**Issue by shu-tom** [crits/crits_services#288]
pyimpfuzzy doesn't support pip install from GitHub.
pyimpfuzzy is uploaded to the PyPI server.
Please update for requirements.txt

https://github.com/crits/crits_services/blob/master/impfuzzy_service/requirements.txt

**Comment by apolkosnik** [comment]
PR #290 addresses this.

**Comment by shu-tom** [comment]
Thank you for pull request.
