### ISSUE TITLE
Add additional PDF feature extraction

### ISSUE THREAD

**Issue by moshekaplan** [crits/crits_services#296]
I'd like to add functionality to extract the following features from a PDF file:

- Links
- OpenAction
- JS

Pull request #103 appears to implement the OpenAction and JS components, leaving only the link extraction feature.

I've already written Python code to extract links from PDFs, based on [PyPDF2](https://pypi.python.org/pypi/PyPDF2/1.26.0), available here: https://github.com/moshekaplan/pdf_analysis_tools/blob/master/pdf_links.py

PyPDF2 is BSD-licensed. My code can be re-licensed to whatever will be easiest to integrate into crits.

**Comment by TheDr1ver** [comment]
The DataMiner patch submitted in #308 should handle the link extraction when links are visible in the PDF's strings, or if links are included in the Raw Data generated by pdf2txt, DataMiner should be able to extract those as well. It's not exactly direct integration with the pdfinfo service, but it should at least get the job done.

**Comment by moshekaplan** [comment]
Sounds good to me.
