### ISSUE TITLE
Results of pdfinfo_service doesnt change.

### ISSUE THREAD

**Issue by boddumanohar** [crits/crits_services#303]
When I do `python pdfparser.py --stats $pdffile` I get an output 
```
{
   "Comments":0,
   "XREF":0,
   "Trailer":0,
   "StartXref":0,
   "IndirectObject":0
}
```

No matter What pdf file I take , I am getting the same output.
I''ve even taken a malicious pdf file generated from `msfconsole` even then it given this same output

Infact when I dug into my pdf file and I saw that they indeed have a `comments` and `XREF`.
 Do the program count special occurrence? 
Do any one actually have any pdf that generated different results?

**Comment by apolkosnik** [comment]
perhaps we need to update to the more up-to-date version of the pdf-parser.

**Comment by boddumanohar** [comment]
Ok two quick questions
1. can I see a pdf where it actually shows a different a different result? 
2. When does the code increment the values of attributes?

**Comment by apolkosnik** [comment]
That's a good question to the author of pdf-parser ... see https://blog.didierstevens.com/programs/pdf-tools/

**Comment by boddumanohar** [comment]
I've already dropped him a mail addressing the problem 20 hours ago. But he hasn't reply yet. May be I should wait for more time or can you guys(  CRITs ) contact him and ask for resolution technique?

**Comment by boddumanohar** [comment]
#304 solves this issue

**Comment by boddumanohar** [comment]
#304
