### ISSUE TITLE
TAXII server problem

### ISSUE THREAD

**Issue by zacharycheng** [crits/crits_services#326]
When I try to poll feeds from the taxii server, I got the "_insert() takes at most 4 arguments (6 given)" error. Any ideas about what have I done wrong? Thanks.

**Comment by brlogan** [comment]
Are you sure you have the proper versions of CybOX, STIX, and TAXII installed?

**Comment by zacharycheng** [comment]
I am not sure if I have installed the right versions of them. 
I just ran the bootstrap script in the crits_services folder I cloned. How can I check whether or not I installed the right versions of them?
Thanks.

**Comment by brlogan** [comment]
You should be able to run `pip list` or `pip freeze` to see which versions you have.  You can compare that to the requirements listed in https://github.com/crits/crits_services/blob/master/taxii_service/requirements.txt

**Comment by zacharycheng** [comment]
Yes, that's the right version I installed after I checked but the error is still showing on the webpage

**Comment by zacharycheng** [comment]
Somehow, I have successfully polled some feeds from the taxii server, but I got the following error:
[![screenshot from 2017-09-27 15-31-57](https://user-images.githubusercontent.com/17289377/30901409-322181cc-a39a-11e7-97b0-fc950892c9e3.png)](url)

Is there anybody having an idea about what should I do to correct it? Thank you!!

**Comment by brlogan** [comment]
Are you polling from a public TAXII server? It seems that whatever you're receiving isn't quite what the service is expecting.

**Comment by zacharycheng** [comment]
I am polling from the hail a taxii server. All the configures are same as the example in the folder.

**Comment by brlogan** [comment]
Hey @zacharycheng, did you ever figure this out? I just posted a bunch of updates for the TAXII Service in #333. Give them a try and let me know if that solves your problem. Thanks!
