### ISSUE TITLE
peinfo broken on pe32+ (64 bit) binaries

### ISSUE THREAD

**Issue by wxsBSD** [crits/crits_services#52]
Running the peinfo service on 64bit binaries causes an error. The error is:

```
Error running service: Bitstrings must have the same length for ^ operator.
```

I've tracked it down to the first XOR operation. I'm curious if bumping the first slice to be [0:8] is the right fix? I don't have time right now to track it down, but if someone does I'd be happy.

```
        #image characteristics
        img_chars = bitstring.BitArray(hex(exe.FILE_HEADER.Characteristics))
        #pad to 16 bits
        img_chars = bitstring.BitArray(bytes=img_chars.tobytes())
        img_chars_xor = img_chars[0:7] ^ img_chars[8:15]
```

**Comment by wxsBSD** [comment]
Turns out peinfo implementations that are out there (totalhash and viper) are broken. Viper is the least broken in that it runs on 64bit binaries and uses the correct slices, but it is not accurate to implementation described in the paper. My best guess is the viper implementation fixed the bugs in totalhash source only. For more information you should check this out:

https://gist.github.com/wxsBSD/07a5709fdcb59d346e9e

**Comment by mrichard91** [comment]
Since this failure breaks all other results it seems reasonable to do a length check and return no value if it fails? Currently if it fails no other attributes are recorded and the service fails.

**Comment by wxsBSD** [comment]
The patch I linked to should be applied or pehash should be removed as it is not trustworthy anyways. I can submit a PR to fix the 64bit problem tonight.
